version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=paydb
      - POSTGRES_USER=payuser
      - POSTGRES_PASSWORD=paypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payuser -d paydb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: